# Generated by Django 3.1.2 on 2020-10-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Camera ID')),
                ('cam_fire_danger', models.CharField(max_length=64, verbose_name='Fire danger')),
                ('cam_time', models.CharField(max_length=64, verbose_name='Time')),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
